# Generated by Django 5.1.7 on 2025-03-27 16:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='description',
        ),
        migrations.AlterField(
            model_name='departement',
            name='nom_depart',
            field=models.CharField(choices=[('brigade_joie', 'Brigade La Joie'), ('brigade_fidelite', 'Brigade Fidélité'), ('brigade_charite', 'Brigade Charité'), ('brigade_patience', 'Brigade Patience'), ('brigade_paix', 'Brigade Paix'), ('brigade_bienveillance', 'Brigade Bienveillance'), ('brigade_amour', 'Brigade Amour'), ('brigade_foi', 'Brigade Foi'), ('brigade_bonte', 'Brigade Bonté'), ('brigade_maitrise_de_soi', 'Brigade Maîtrise de Soi')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_naissance',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 3, 27))]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenoms',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
