# Generated by Django 5.1.7 on 2025-03-27 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_departement_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='evenement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.evenement'),
        ),
    ]
