# Generated by Django 5.1.7 on 2025-03-27 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_presence_evenement'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='utilisateur',
            field=models.ManyToManyField(related_name='departements', to='application.utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='application.departement'),
        ),
    ]
