# Generated by Django 5.1.7 on 2025-03-29 20:53

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_departement_utilisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_naissance',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 3, 29))]),
        ),
    ]
