# Generated by Django 5.1.7 on 2025-04-02 02:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_evenement_image_alter_utilisateur_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='date_naissance',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 4, 2))]),
        ),
    ]
