# Generated by Django 5.1.7 on 2025-04-12 18:58

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_evenement_organisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='date_naissance',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 4, 12))]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='application.departement'),
        ),
    ]
